# Generated by Django 3.0.4 on 2020-10-10 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forteID', models.CharField(max_length=200)),
                ('crossDocName', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 15, 10, 14, 432802))),
                ('endTime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 15, 10, 14, 432844))),
                ('totalTime', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CrossDocAnnotation',
        ),
        migrations.AddField(
            model_name='crossdoc',
            name='nameHash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
