# Generated by Django 3.0.4 on 2020-04-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0002_document_ontology'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('textPack', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
