# Generated by Django 3.0.4 on 2020-10-10 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0002_auto_20201010_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossdoc',
            name='nameHash',
        ),
        migrations.AddField(
            model_name='crossdoc',
            name='idHash',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='crossdoc',
            name='packID',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='packID',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='annotationlog',
            name='endTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 18, 16, 22, 817284)),
        ),
        migrations.AlterField(
            model_name='annotationlog',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 18, 16, 22, 817242)),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
