# Generated by Django 3.0.4 on 2020-05-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0003_auto_20200401_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDocAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('turkID', models.TextField()),
                ('textPack', models.TextField()),
                ('ontology', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='crossdoc',
            name='ontology',
            field=models.TextField(default=''),
        ),
    ]
