# Generated by Django 3.0.7 on 2020-08-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0006_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
