# Generated by Django 3.0.7 on 2020-10-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0007_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('viewer_project', 'Can view the project'), ('editor_project', 'Can edit the project'))},
        ),
    ]
