# Generated by Django 3.0.4 on 2021-01-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlpviewer_backend', '0011_auto_20210113_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossdoc',
            name='packID',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='packID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
