# Generated by Django 3.0.2 on 2020-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ontology',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
