# Generated by Django 3.0.7 on 2020-07-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0002_document_ontology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('ontology', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='ontology',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stave_backend.Project'),
        ),
    ]
