# Generated by Django 3.0.7 on 2020-07-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0003_auto_20200712_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
