# Generated by Django 3.0.7 on 2020-07-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0004_auto_20200712_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='ontology',
        ),
    ]
