# Generated by Django 3.0.4 on 2021-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0005_remove_document_ontology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=models.TextField(default=''),
        ),
    ]
