# Generated by Django 3.0.7 on 2020-12-03 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stave_backend', '0005_remove_document_ontology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('read_project', 'Can read the project'), ('edit_annotation', 'Can edit annotation'), ('edit_text', 'Can edit the document'), ('edit_project', 'Can edit the project'), ('remove_project', 'Can remove the project'), ('new_project', 'Can create in the project'))},
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
