# Generated by Django 3.0.4 on 2021-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0006_project_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='multi_ontology',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='single_pack', max_length=100),
        ),
    ]
