# Generated by Django 3.0.7 on 2020-12-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0006_auto_20201203_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=models.TextField(default=''),
        ),
    ]
