# Generated by Django 3.0.4 on 2021-01-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0007_auto_20210111_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('textPack', models.TextField()),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossdocs', to='stave_backend.Project')),
            ],
        ),
    ]
