# Generated by Django 3.0.4 on 2021-01-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0009_auto_20201203_0318'),
        ('stave_backend', '0008_crossdoc'),
    ]

    operations = [
    ]
