# Generated by Django 3.0.4 on 2021-01-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0010_merge_20210113_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='config',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
