# Generated by Django 3.1.3 on 2021-02-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0011_auto_20210113_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='multi_ontology',
        ),
    ]
