# Generated by Django 3.1.4 on 2021-03-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0012_remove_project_multi_ontology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigner', models.CharField(default='auto', max_length=200)),
                ('assignee', models.CharField(max_length=200)),
                ('pack_table', models.CharField(default='stave_backend_document', max_length=200)),
                ('job_content', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=200)),
                ('document', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='stave_backend.project')),
            ],
        ),
    ]
