# Generated by Django 3.1.4 on 2021-03-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0013_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='document',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='stave_backend.document'),
        ),
    ]
