# Generated by Django 3.1.4 on 2021-03-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0014_auto_20210322_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='document',
        ),
    ]
