# Generated by Django 3.1.4 on 2021-03-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0015_remove_job_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('read_project', 'Can read the project'), ('edit_annotation', 'Can edit annotation'), ('edit_text', 'Can edit the document'), ('edit_project', 'Can edit the project'), ('remove_project', 'Can remove the project'), ('new_project', 'Can create in the project'), ('create_job', 'Can create a job'), ('query_job', 'Can query jobs'), ('update_job', 'Can update jobs'))},
        ),
    ]
