# Generated by Django 3.1.4 on 2021-04-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stave_backend', '0016_auto_20210331_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('read_project', 'Can read the project'), ('edit_annotation', 'Can edit annotation'), ('edit_text', 'Can edit the document'), ('edit_project', 'Can edit the project'), ('remove_project', 'Can remove the project'), ('new_project', 'Can create in the project'))},
        ),
    ]
